-- Dedicated Hugging Face pool metadata. Credentials intentionally remain in
-- accounts so existing concurrency, usage-log and billing foreign keys keep
-- working, but HF accounts are not linked through account_groups and therefore
-- never enter the legacy scheduler snapshot.

CREATE TABLE IF NOT EXISTS hf_pools (
    id BIGSERIAL PRIMARY KEY,
    group_id BIGINT NOT NULL REFERENCES groups(id) ON DELETE RESTRICT,
    name VARCHAR(100) NOT NULL,
    base_url TEXT NOT NULL DEFAULT 'https://router.huggingface.co',
    priority INTEGER NOT NULL DEFAULT 50 CHECK (priority BETWEEN 0 AND 1000000),
    weight INTEGER NOT NULL DEFAULT 100 CHECK (weight BETWEEN 1 AND 1000000),
    status VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled')),
    models JSONB NOT NULL DEFAULT '["*"]'::jsonb,
    failure_threshold INTEGER NOT NULL DEFAULT 5 CHECK (failure_threshold BETWEEN 1 AND 1000),
    circuit_cooldown_seconds INTEGER NOT NULL DEFAULT 30 CHECK (circuit_cooldown_seconds BETWEEN 1 AND 86400),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS hf_pools_group_name_active_uidx
    ON hf_pools (group_id, LOWER(name)) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS hf_pools_group_schedule_idx
    ON hf_pools (group_id, priority, id) WHERE deleted_at IS NULL AND status = 'active';

-- A token fingerprint is a keyed HMAC generated by the application. The
-- partial unique index deduplicates both existing rows and one bulk import
-- without exposing token plaintext.
CREATE UNIQUE INDEX IF NOT EXISTS accounts_hf_token_fingerprint_active_uidx
    ON accounts ((extra ->> 'hf_token_fingerprint'))
    WHERE deleted_at IS NULL
      AND platform = 'huggingface'
      AND (extra ->> 'hf_token_fingerprint') IS NOT NULL;

CREATE INDEX IF NOT EXISTS accounts_hf_pool_schedule_idx
    ON accounts ((extra ->> 'hf_pool_id'), priority, id)
    WHERE deleted_at IS NULL AND platform = 'huggingface';

CREATE INDEX IF NOT EXISTS accounts_hf_recovery_idx
    ON accounts ((extra ->> 'hf_recover_at'), id)
    WHERE deleted_at IS NULL
      AND platform = 'huggingface'
      AND status = 'disabled'
      AND (extra ->> 'hf_recover_at') IS NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'accounts_hf_apikey_type_check'
    ) THEN
        ALTER TABLE accounts ADD CONSTRAINT accounts_hf_apikey_type_check
            CHECK (platform <> 'huggingface' OR type = 'apikey') NOT VALID;
    END IF;
END $$;

-- HF credentials are scheduled only through hf_pools. A database guard keeps
-- future generic/bulk code paths from accidentally inserting them into the
-- legacy account_groups snapshot.
CREATE OR REPLACE FUNCTION reject_hf_account_group_binding()
RETURNS TRIGGER AS $$
BEGIN
    IF EXISTS (SELECT 1 FROM accounts WHERE id = NEW.account_id AND platform = 'huggingface') THEN
        RAISE EXCEPTION 'Hugging Face accounts must not be bound through account_groups'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_reject_hf_account_group_binding ON account_groups;
CREATE TRIGGER trg_reject_hf_account_group_binding
    BEFORE INSERT OR UPDATE OF account_id ON account_groups
    FOR EACH ROW EXECUTE FUNCTION reject_hf_account_group_binding();

-- Keep pool ownership and group lifecycle valid even if a future code path
-- bypasses the dedicated service.
CREATE OR REPLACE FUNCTION validate_hf_pool_group()
RETURNS TRIGGER AS $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM groups
        WHERE id = NEW.group_id AND platform = 'huggingface' AND deleted_at IS NULL
    ) THEN
        RAISE EXCEPTION 'Hugging Face pools require an active Hugging Face group record'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_validate_hf_pool_group ON hf_pools;
CREATE TRIGGER trg_validate_hf_pool_group
    BEFORE INSERT OR UPDATE OF group_id ON hf_pools
    FOR EACH ROW EXECUTE FUNCTION validate_hf_pool_group();

CREATE OR REPLACE FUNCTION protect_hf_pool_group_lifecycle()
RETURNS TRIGGER AS $$
BEGIN
    IF EXISTS (SELECT 1 FROM hf_pools WHERE group_id = OLD.id AND deleted_at IS NULL)
       AND (NEW.platform IS DISTINCT FROM OLD.platform
            OR (OLD.deleted_at IS NULL AND NEW.deleted_at IS NOT NULL)) THEN
        RAISE EXCEPTION 'Delete Hugging Face pools before changing or deleting their group'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_protect_hf_pool_group_lifecycle ON groups;
CREATE TRIGGER trg_protect_hf_pool_group_lifecycle
    BEFORE UPDATE OF platform, deleted_at ON groups
    FOR EACH ROW EXECUTE FUNCTION protect_hf_pool_group_lifecycle();
